# Generated by Django 2.0b1 on 2017-11-14 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Име на авторот', max_length=150, verbose_name='Име')),
            ],
            options={
                'db_table': 'biblioteka_author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=30)),
                ('title', models.CharField(help_text='Наслов на книгата', max_length=250, verbose_name='Наслов')),
                ('slug', models.SlugField(max_length=250)),
                ('release_year', models.IntegerField(blank=True, help_text='Година на издавање', null=True, verbose_name='Година')),
                ('tags', models.CharField(blank=True, help_text='Сепаратор=запирка(,)', max_length=300, null=True, verbose_name='Тагови')),
                ('description', models.CharField(blank=True, help_text='опис на книгата', max_length=500, null=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, help_text='Стави права слика (не фејк)!', null=True, upload_to='books/', verbose_name='Слика')),
                ('external_image_url', models.URLField(blank=True, help_text='Слика која ќе се чува на серверот', null=True, verbose_name='Надворешна слика')),
                ('quantity', models.IntegerField(default=1, help_text='Вкупна количина на книги', verbose_name='Количина')),
                ('in_stock', models.IntegerField(default=1, help_text='Колку вкупно копии има преостанато во библиотеката', verbose_name='Преостанати копии')),
                ('donated_by', models.CharField(blank=True, help_text='Од кого е донирана книгата', max_length=128, null=True, verbose_name='Донирана од')),
                ('authors', models.ManyToManyField(help_text='Авотри на книгата', to='biblioteka.Author')),
            ],
            options={
                'db_table': 'biblioteka_book',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Назив')),
                ('iso_name', models.CharField(max_length=5, verbose_name='ISO-2 Кратенка')),
            ],
            options={
                'db_table': 'biblioteka_language',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назив на издавачот', max_length=30, verbose_name='Назив')),
            ],
            options={
                'db_table': 'biblioteka_publisher',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_on', models.DateTimeField(auto_now_add=True)),
                ('returned_on', models.DateTimeField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.Book')),
                ('rented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biblioteka_rental',
            },
            managers=[
                ('default', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.Book')),
                ('reserved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biblioteka_reservation',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='lang',
            field=models.ForeignKey(blank=True, help_text='Јазик', null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteka.Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='Издавач на книгата', null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteka.Publisher'),
        ),
    ]
